POST https://localhost:7117/api/reports
Content-Type: application/json

{
  "ReportType": "SingleProductReport",
  "FileId": "10DM12-03-2024_Damian",
  "OperatorName": "David Molina",
  "Folio": "123456",
  "Date": "2024-03-12T00:00:00Z",
  "ClientName": "Damian Lillard",
  "ClientId": "16.234.743-K",
  "TruckCompany": "Milwaukee Bucks",
  "TruckDriver": "Doc Rivers",
  "TruckDriverId": "12.345.212-2",
  "TruckPlate": "CHDK23",
  "Origin": "Milwaukee",
  "ProductType": "Metro Ruma",
  "ProductName": "Nativo",
  "TruckHeight": 1.26,
  "TruckLength": 2.05,
  "Banks": 6,
  "PalomeraHeight": 1.56,
  "PalomeraWidth": 1.85,
  "FinalQuantity": 25
}

// ProductType: Metro Ruma -> ProductName: Nativo, Oregon, Otro
// ProductType: Lena -> ProductName: Nativo, Oregon, Encino, Mezcla de Oregon-Nativo
