#POST https://bosquesnalcahue-api.azurewebsites.net/api/reports/upload-report
POST https://localhost:7117/api/reports/upload-report
Content-Type: application/json
api-key: MarrichiweuPupeiPuLamngen
 
{
  "ReportType": "SingleProductReport",
  "FileId": "15DM10-13-24_Anthony",
  "OperatorName": "David Molina",
  "Folio": "15DM10/13/24-12:30",
  "Date": "2024-10-13T00:00:00Z",
  "ClientName": "Anthony Edwards",
  "ClientId": "19.934.993-1",
  "TruckCompany": "Minnesota Timberwolves",
  "TruckDriver": "Chris Finch",
  "TruckDriverId": "13.245.512-2",
  "TruckPlate": "CHDK23",
  "Origin": "Minnesota",
  "ProductType": "Leña",
  "ProductName": "Mezcla Oregon-Nativo",
  "TruckHeight": 1.26,
  "TruckLength": 2.05,
  "Banks": 6,
  "PalomeraHeight": 1.56,
  "PalomeraWidth": 1.85,
  "FinalQuantity": 25
}

# ProductType: Metro Ruma -> ProductName: Nativo, Oregon, Otro
# ProductType: Leña -> ProductName: Nativo, Oregon, Encino, Mezcla de Oregon-Nativo

###
